#define STRING_TASKMANAGER_VERSION	"v1.0"
#define STRING_COPYRIGHT		"Copyrigth (c) @ M2X, hust maotianjiao"
#define STRING_AUTHOR			"maotianjiao"
#define STRING_TASKMANAGER		"TaskManager"
#define STRING_PROCESSOR		"Processor:"
#define STRING_HOSTNAME			"Hostname:"
#define STRING_VERSION			"Version:"
#define STRING_UPTIME			"Uptime:"
#define STRING_START_TIME		"Start Time:" 
#define STRING_MORE			"more>>"
#define STRING_PROCESSES		"Processes"
#define STRING_PERFORMANCE		"Performance"
#define STRING_SYSINFO			"SysInfo"
#define STRING_CPU_USAGE		"CPU Usage"
#define STRING_MEM_USAGE		"Memory Usage"
#define STRING_PID			"PID"
#define STRING_PPID			"PPID"
#define STRING_MEMORY			"Memory"
#define STRING_PRIORITY			"Priority"
#define STRING_NAME			"Name"
#define STRING_STATUS			"Status"
#define STRING_FILE			"/File"
#define STRING_FILE_NEW_TASK		"/File/New Task"
#define STRING_FILE_QUIT		"/File/Quit"
#define STRING_HELP			"/Help"
#define STRING_HELP_ABOUT		"/Help/About TaskManager"
#define STRING_SHUTDOWN			"/ShutDown"
#define STRING_SHUTDOWN_SHUTDOWN	"/ShutDown/ShutDown"
#define STRING_SHUTDOWN_REBOOT	"/ShutDown/Reboot"
#define STRING_NOTICE			"Notice"
#define STRING_SHUTDOWN_NOTICE	"Are you sure you want to shutdown?"
#define STRING_REBOOT_NOTICE		"Are you sure you want to reboot?"
#define STRING_RUN_PROGRAM		"Run a program"
#define STRING_CPU_USAGE_GRAPH	"CPU Usage Graph"
#define STRING_MEM_USAGE_GRAPH	"Memory Usage Graph"
#define STRING_SWAP_USAGE_GRAPH	"Swap Usage Graph"
#define STRING_KILL_PROCESS		"Kill Process"
#define STRING_DETAIL			"Detail"
#define STRING_FIND			"Find"
#define STRING_REFRESH			"Refresh"
#define STRING_PROCESS_INFO		"Process Information"
#define STRING_KILL_NOTICE		"Are you sure to kill this process?"


