#define STRING_TASKMANAGER	"TaskManager"
#define STRING_PROCESSOR	"Processor:"
#define STRING_HOSTNAME		"Hostname:"
#define STRING_VERSION		"Version:"
#define STRING_UPTIME		"Uptime:"
#define STRING_START_TIME	"Start Time:" 
#define STRING_MORE		"more>>"
#define STRING_PROCESSES	"Processes"
#define STRING_PERFORMANCE	"PerforMance"
#define STRING_SYSINFO		"SysInfo"
#define STRING_CPU_USAGE	"CPU Usage"
#define STRING_MEM_USAGE	"Memory Usage:"
#define STRING_PID		"PID"
#define STRING_PPID		"PPID"
#define STRING_MEMORY		"Memory"
#define STRING_PRIORITY		"Priority"
#define STRING_NAME		"Name"
#define STRING_STATUS		"Status"
#define STRING_FILE		"/_File"
#define STRING_FILE_NEW_TASK	"/File/_New Task"
#define STRING_FILE_QUIT	"/File/_Quit"
#define STRING_HELP		"/_Help"
#define STRING_HELP_ABOUT	"/Help/_About"
#define STRING_OK			"OK"
#define STRING_CANCEL		"Cancel"
#define STRING_NOTICE		"Notice"
#define STRING_RUN_PROGRAM	"Run a program"

