#define STRING_TASKMANAGER	"任务管理器"
#define STRING_PROCESSOR	"处理器:"
#define STRING_HOSTNAME		"主机名:"
#define STRING_VERSION		"版本号:"
#define STRING_UPTIME		"持续运行时间:"
#define STRING_START_TIME	"系统启动时间:" 
#define STRING_MORE		"详细>>"
#define STRING_PROCESSES	"进程"
#define STRING_PERFORMANCE	"性能"
#define STRING_SYSINFO		"系统信息"
#define STRING_CPU_USAGE	"CPU 使用率"
#define STRING_MEM_USAGE	"内存使用率:"
#define STRING_PID		"PID"
#define STRING_PPID		"PPID"
#define STRING_MEMORY		"内存"
#define STRING_PRIORITY		"优先级"
#define STRING_NAME		"名称"
#define STRING_STATUS		"状态"
#define STRING_FILE		"/_文件"
#define STRING_FILE_NEW_TASK	"/文件/_新建任务"
#define STRING_FILE_QUIT	"/文件/_退出"
#define STRING_HELP		"/_帮助"
#define STRING_HELP_ABOUT	"/帮助/_关于"
#define STRING_OK			"确定"
#define STRING_CANCEL		"取消"
#define STRING_NOTICE		"提示"
#define STRING_RUN_PROGRAM	"运行一个应用程序"

